name: SonarCloud
on:
  push:
    branches: [ master ]
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  build-and-analyze:
    name: Build and Analyze
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/openatv/enigma2-buildenv/enigma2-buildenv:latest
      options: --user root

    env:
#      SONAR_SCANNER_VERSION: 4.7.0.2747
#      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
    - name: Install libraries
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -q update
        sudo apt remove -y libunwind-14-dev
        sudo apt-get install g++-11
        sudo apt-get install linux-libc-dev
        sudo apt-get install git
        sudo apt-get install build-essential
        sudo apt-get install automake
        sudo apt-get install libtool
        sudo apt-get install python3.10-dev
        sudo apt-get install zlib1g-dev
        sudo apt-get install gettext
        sudo apt-get install swig
        sudo apt-get install libgstreamer1.0-dev
        sudo apt-get install libgstreamer-plugins-base1.0-dev
        sudo apt-get install libfreetype6-dev
        sudo apt-get install libsigc++-2.0-dev
        sudo apt-get install libfribidi-dev
        sudo apt-get install libssl-dev
        sudo apt-get install libavahi-client-dev
        sudo apt-get install libjpeg-turbo8-dev
        sudo apt-get install libgif-dev
        sudo apt-get install libcurl4-openssl-dev

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v2

    - uses: actions/setup-python@v4
        with:
        python-version: '3.12'
          
    - name: Build enigma2 dependencies
      env:
        CC: "gcc-13"
        CXX: "g++-13"
      run: |
        echo "installing libdvbsi++"
        pushd .
        cd /tmp
        git clone --depth 1 https://github.com/oe-alliance/libdvbsi.git
        cd libdvbsi
        autoreconf -i
        ./configure
        make
        sudo make install
        popd
        echo "installing tuxbox"
        pushd .
        cd /tmp
        git clone --depth 1 https://github.com/oe-alliance/tuxtxt.git
        cd tuxtxt/libtuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
        cd ../tuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
        popd

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6

      - name: Run Build Wrapper
        env:
          CC: gcc-14
          CXX: g++-14
        run: |
          sed -i 's/include lib main data po tools/include lib main tools/g' Makefile.am
          autoreconf -i

          export LIBS="-L/usr/lib/x86_64-linux-gnu -lpython3.13"
          export CPPFLAGS="-I/usr/include/python3.13"

          ./configure \
            PYTHON=python3.13 \
            --with-libsdl=no \
            --with-boxtype=nobox \
            --enable-dependency-tracking \
            ac_cv_prog_c_openmp=-fopenmp \
            --with-gstversion=1.0 \
            --with-textlcd

          build-wrapper-linux-x86-64 \
            --out-dir "${BUILD_WRAPPER_OUT_DIR}" \
            make

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json
            -Dsonar.verbose=true
            ${{ github.event_name == 'pull_request_target' &&
                format('-Dsonar.pullrequest.key={0} -Dsonar.pullrequest.branch={1} -Dsonar.pullrequest.base={2}',
                github.event.pull_request.number,
                github.event.pull_request.head.ref,
                github.event.pull_request.base.ref) || '' }}
