name: updatepot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: '8.0'

      - name: updatepot
        run: |
          sudo apt-get -q update
          sudo apt-get install gettext
          git config --global user.email "bot@openspa.info"
          git config --global user.name "spa enigma po Bot"
          git config advice.addignoredfile false
          git clean -fd
          git checkout 8.0
          cd po
          ./updatepot.sh
          cd ..
          git add -u
          git add * || :
          git commit -m "pot update"
          git remote add upstream https://${GITHUB_TOKEN}@github.com/openspa/dvbapp2.git > /dev/null 2>&1
          git push --quiet upstream 8.0 || echo "failed to push with error $?"
